### ISSUE TITLE
Not working of console in FreeRTOS domain 

### ISSUE THREAD

**Issue by chochanghwan** [GaloisInc/FreeRTOS-Xen#1]
Hello, 

Now I am porting FreeRTOS-Xen to xen 4.5 ARM on ARNDALE board. 
the test environment is below 
1. xen 4.5
2. Dom0 - Linux 3.18
3. DomU - FreeRTOS
After creating FreeRTOS, I got two domains, linux and freertos.
------------------------------------------------------------------------------------------------
 root@Dom0:~# xl list
Name                                        ID   Mem VCPUs      State   Time(s)
Domain-0                                     0   128     2     r-----      16.9
DomU01                                       1   128     1     ------       6.7
DomU02                                       2    32     1     r-----       3.7
------------------------------------------------------------------------------------------------

And I try to switch console to freeRTOS domain, but the system hold.

------------------------------------------------------------------------------------------------
root@Dom0:~# xl console DomU02
...... no response before power off.............................
------------------------------------------------------------------------------------------------

**Comment by jtdaugherty** [comment]
To debug further, you'll need to rebuild Xen with `make verbose=y` to enable the emergency debug console hypercall, and then you might consider rebuilding FreeRTOS-Xen with the `DEBUG` settings enabled (see individual C/header sources for those).  Doing this will result in console output from FreeRTOS very early in its boot process, even before some Xen services have been configured, and should provide more information so we can see what is going on.

**Comment by jtdaugherty** [comment]
Also, have you familiarized yourself with the "future work & caveats" section of the README?

https://github.com/GaloisInc/FreeRTOS-Xen#future-work--caveats

This will be important since some things are bound to break on Xen > 4.4 and that section provides some insight into what to look for first.

**Comment by chochanghwan** [comment]
Hello, 
Thank you for your reply so fast. 
I followed your guide, but I did not see any thing.

Our company have been reviewing type-1 hypervisor(xen arm, xvisor, etc) for automotive. I thought Our automotive application have variant OS, such as linux, rtos, autosar and baremetal. 

Now I have been checking the feasibility for open source hypervisor.

**Comment by chochanghwan** [comment]
Hello, 

I saw your youtube that you presented the porting freertos with linux to arndale board. 
I think that my test environment is very similar to that in your youtube, but I don't get anything.

what is the wrong ?

**Comment by jtdaugherty** [comment]
Have you tried to rebuild with the `DEBUG` options I mentioned, and have you rebuilt Xen with `make verbose=y`?

**Comment by chochanghwan** [comment]
Thank you so much. 

I had built xen-4.5.0 with setting "make verbose=y dist-xen XEN_TARGET_ARCH=arm32 CROSS_COMPILE=arm-linux-gnueabihf-" and I had enabled FreeRTOS with below items.

./Source/tasks.c:72:#define TASK_DEBUG 1
./Source/portable/GCC/ARM7_CA15_Xen/port.c:33:#define PORT_DEBUG 1
./Source/portable/GCC/ARM7_CA15_Xen/gic.c:28:#define GIC_DEBUG 1
./Source/portable/GCC/ARM7_CA15_Xen/mmu.c:26:#define DEBUG 1
./Demo/CORTEX_A15_Xen_GCC/platform/xen/gnttab.c:33:#define DEBUG 1
./Demo/CORTEX_A15_Xen_GCC/platform/xen/hypervisor.c:34:#define DEBUG 1
./Demo/CORTEX_A15_Xen_GCC/platform/libIVC.c:46:#define DEBUG 1

but I don't get success. 

I tried it with " #define configUSE_XEN_CONSOLE  1"   but also I don't.

I have been testing with guide "http://ssup2.iptime.org/wiki/Xen_4.5.0_on_Arndale". if there are different with your method, let me know. Now I don't know how to use serial(UART) at each Dom U.
if I get solved with this problem, next I'll develop car line tracking with sensor module under xen+freeRTOS.

**Comment by chochanghwan** [comment]
And I can't connect to DomU(FreeRTOS console) with the command " xl console <domain> or xl create -c <config file>"

**Comment by jtdaugherty** [comment]
If you have done all that and you still aren't getting any output, that strongly suggests that something low-level in the boot setup code is going wrong, or that the binary is just being built for the wrong architecture.  There is assembly code for dumping the register state; you might consider inserting calls to that macro, which can be found in
```
Source/portable/GCC/ARM7_CA15_Xen/asm/dumpregs.s
```
It's also possible that the hypercall for console I/O is just plain broken, in which case you'll have to check the Xen hypercall number for `HYPERVISOR_console_io`, along with its argument, `CONSOLEIO_write`.  FreeRTOS uses the values in

```
Demo/CORTEX_A15_Xen_GCC/platform/asm/hypercalls.s
```

**Comment by chochanghwan** [comment]
Thank you so much.

I tried something you mentioned. is it right?

I got information about example binary. I thought it is right to ARM. 
.............................................................................................................................
$file Example.bin 
Example.bin: Linux kernel ARM boot executable zImage (little-endian)
.............................................................................................................................

I got right that the same in both.(./xen/include/public/xen.h:82:#define __HYPERVISOR_console_io           18)


As to README File, I must install xen on pc( in my case, ubuntu14.04). I only install libxen-dev package on my PC. is it problem? if problem, how to do? 
And in case of compiler, I use the version "arm-2013.05". is it problem? if problem, how to do? 

BR.
ch cho.

**Comment by jtdaugherty** [comment]
If those values checked out, then I'm not sure what else I can do to help.  If you aren't getting any debugging output at all and the VM is crashing early, that's a sign that either it is never starting in the first place or it is crashing very early in the boot setup procedure, which suggests some kind of disagreement either with the hardware (unlikely) or hypervisor (more likely).
