### ISSUE TITLE
Compile Error 

### ISSUE THREAD

**Issue by chochanghwan** [GaloisInc/FreeRTOS-Xen#2]
Hello, 

For building the core, I have trouble to build it on ubuntu14.04/64bit machine with installing libxen-dev package only. 

.........................................Error Log............................................
arm-none-eabi-gcc -c   -Wall -Werror -I ./include -I ./platform/include -I ./platform/minlibc/include/ -I ../../Source/include -I ../Common/include -I ../../Source/portable/GCC/ARM7_CA15_Xen/include -I /usr/include -D XEN_HAVE_PV_GUEST_ENTRY=1 -D CA15_XEN_GCC -mcpu=cortex-a15 -mfpu=vfpv4 -fomit-frame-pointer -fno-strict-aliasing -nostdlib -x assembler-with-cpp platform/asm/shared_info.s -o platform/asm/shared_info.o
cc1: error: include location "/usr/include" is unsafe for cross-compilation [-Werror=poison-system-directories]
cc1: all warnings being treated as errors
make: *** [platform/asm/shared_info.o] Error 1
............................................................................................................

BR
Thanks

**Comment by jtdaugherty** [comment]
It looks like the documentation needs to be updated; when I developed this I did not use `libxen-dev` headers in `/usr`.  Instead I used Xen headers from a clone of the Xen source tree.  You might consider trying that and setting the Xen prefix accordingly to avoid using `/usr`.

**Comment by chochanghwan** [comment]
Thanks, 

It set with "XEN_PREFIX =./xen-4.5.0/xen", but still be error to find header file.
.................................................................................................................................
./include/freertos/os.h:24:21: fatal error: xen/xen.h: No such file or directory
.................................................................................................................................

BR

Thanks...

**Comment by charlescho64** [comment]
I am very confusing in setting the environment to compile this project. If you are ok to let me know about your setting condition, I hope you give a chance to get happy to solve this issue.

**Comment by jtdaugherty** [comment]
@chochanghwan - a relative path for `XEN_PREFIX` will almost certainly cause the problem you are seeing.  Try an absolute path instead.

**Comment by chochanghwan** [comment]
Thanks, but still have problem to compile with absolute or relative path. 
----------------------------------------------------------------------------------------------------------
In file included from ./platform/include/platform/console.h:40:0,
                 from assert.c:21:
./include/freertos/os.h:24:21: fatal error: xen/xen.h: No such file or directory
compilation terminated.
make: *** [assert.o] Error 1
----------------------------------------------------------------------------------------------------------

**Comment by jtdaugherty** [comment]
Can you do some more investigation to see whether `xen.h` exists anywhere on your system? Then you can tell whether perhaps your `XEN_PREFIX` is wrong.

**Comment by lchan12** [comment]
I had same issue and I solved it by fixing XEN_PREFIX in Makefile and copying xen headers.

1. Find the directory "public" in your xen project. In my case, ...../xen-4.5.0/xen/include/public

2. And copy it.
==> cp -rf ...../xen-4.5.0/xen/include/public ....../FreeRTOS-Xen-Master/Demo/CORTEX_A15_Xen_GCC/include

3. rename "include" to "xen"
==> mv ....../FreeRTOS-Xen-Master/Demo/CORTEX_A15_Xen_GCC/include ....../FreeRTOS-Xen-Master/Demo/CORTEX_A15_Xen_GCC/xen

4. modify Makefile.   XEN_PREFIX = ....path/to/xen
==> XEN_PREFIX = ....../xen-4.5.0/xen

5. find "xenstore_lib.h" in xen project. In my case, ...../xen-4.5.0/tools/xenstore/include/xenstore_lib.h

6. copy it.
==> cp ...../xen-4.5.0/tools/xenstore/include/xenstore_lib.h ....../FreeRTOS-Xen-Master/Demo/CORTEX_A15_Xen_GCC/include

7. finished. just built it.
==> cd ...../FreeRTOS-Xen-Master/Demo/CORTEX_A15_Xen_GCC
==> make


*** if you have same error when proceeding "Step 2. Building an application", the solution is also same. Modify Makefile in your "Example" directory. Fix 'XEN_PREFIX'.

**Comment by jtdaugherty** [comment]
@lchan12, thanks for providing the details for what worked for you.  Note that steps 5 and 6 can be avoided entirely just by adding the xenstore_lib.h path to your include path.

**Comment by jtdaugherty** [comment]
Since this ticket hasn't seen any activity in a while, I'm going to close it.  If this is still a problem, feel free to re-open.

**Comment by DAYESS** [comment]
@lchan12  : which toolchain have you used ?

**Comment by lchan12** [comment]
@DAYESS , hi . I used "arm-linux-gnueabihf-" toolchain. 
Download url was ... [https://releases.linaro.org/15.02/components/toolchain/binaries/arm-linux-gnueabihf/gcc-linaro-4.9-2015.02-3-x86_64_arm-linuxgnueabihf.tar.xz](https://releases.linaro.org/15.02/components/toolchain/binaries/arm-linux-gnueabihf/gcc-linaro-4.9-2015.02-3-x86_64_arm-linuxgnueabihf.tar.xz)
but now it is not valid.. and I dont have that toolchain.
I think, however you can find it here: [https://releases.linaro.org/components/toolchain/binaries/](https://releases.linaro.org/components/toolchain/binaries/)

And this may help you :)
[http://ssup2.iptime.org/wiki/Xen_4.5.0_on_Arndale](http://ssup2.iptime.org/wiki/Xen_4.5.0_on_Arndale)
